### ISSUE TITLE
evaluate entity จับประโยคไม่ตรง

### ISSUE THREAD

**Issue by WisTiCeJEnT** [SuttipatNew/evaluate-entity-ranking-info#1]
มีบางประโยคที่หลุดไปเช่น "The problem is brabra" ไม่ได้จับคำว่า brabra แต่จับคำว่า problem แทน

**Comment by stapy127** [comment]
ถ้าในกรณีนั้นให้ติ๊ก problem เป็น Not an aspect ได้เลยครับ
